pipeline {
    agent any

    stages {

        stage('Download Artifact') {
            steps {
                sh '''
                rm -f vproapp.war

                wget -O vproapp.war \
                http://172.31.4.225:8081/repository/maven-releases/QA/vproapp/8-null/vproapp-8-null.war

                echo "Downloaded artifact:"
                ls -lh
                '''
            }
        }

        stage('Deploy to Tomcat') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'tomcat-manager',
                    usernameVariable: 'TOMCAT_USER',
                    passwordVariable: 'TOMCAT_PASS'
                )]) {
                    sh '''
                    curl -v \
                    -u "$TOMCAT_USER:$TOMCAT_PASS" \
                    -T vproapp.war \
                    "http://172.31.39.217:8080/manager/text/deploy?path=/vprofile&update=true"
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Application deployed successfully!'
        }

        failure {
            echo 'Deployment failed.'
        }
    }
}